rplidar_node:
    ros__parameters:
        channel_type: udp
        udp_ip: 10.15.20.23
        udp_port: 8089
        frame_id: laser
        inverted: true
        angle_compensate: false
        scan_mode: Standard
        scan_frequency: 10.0
        max_distance: 2.5
